#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { detectFitWarnings, detectOverlaps } from './diagnostics'
import { generatePhaserSnippets } from './generate'
import { normalizeInput } from './normalize'
import type { MapperInput, MapperOutput } from './types'

type CliArgs = {
  inputPath: string
  jsonOutPath?: string
  phaserOutPath?: string
  width?: number
  height?: number
}

const parseArgs = (argv: string[]): CliArgs => {
  const args: CliArgs = {
    inputPath: '',
  }
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i]
    if (!token) continue
    if (token === '--input') args.inputPath = argv[i + 1] ?? ''
    if (token === '--json') args.jsonOutPath = argv[i + 1] ?? undefined
    if (token === '--phaser') args.phaserOutPath = argv[i + 1] ?? undefined
    if (token === '--width') args.width = Number.parseInt(argv[i + 1] ?? '', 10)
    if (token === '--height') args.height = Number.parseInt(argv[i + 1] ?? '', 10)
  }
  return args
}

const printUsage = (): void => {
  console.info(
    [
      'Usage:',
      '  pnpm stitch:map -- --input <path/to/stitch.json> [--json <out.json>] [--phaser <out.ts>] [--width 768] [--height 1376]',
      '',
      'Example:',
      '  pnpm stitch:map -- --input tools/stitch-phaser-mapper/examples/screen.sample.json --json /tmp/layout.json --phaser /tmp/snippets.ts',
    ].join('\n'),
  )
}

const ensureDirForFile = async (filePath: string): Promise<void> => {
  const dir = path.dirname(filePath)
  await mkdir(dir, { recursive: true })
}

const run = async (): Promise<void> => {
  const args = parseArgs(process.argv.slice(2))
  if (!args.inputPath) {
    printUsage()
    process.exitCode = 1
    return
  }

  const raw = await readFile(args.inputPath, 'utf8')
  const parsed = JSON.parse(raw) as MapperInput
  if (args.width && Number.isFinite(args.width)) parsed.width = args.width
  if (args.height && Number.isFinite(args.height)) parsed.height = args.height

  const normalized = normalizeInput(parsed)
  const overlaps = detectOverlaps(normalized.nodes)
  const fitWarnings = detectFitWarnings(normalized.nodes, normalized.width, normalized.height)
  const phaserSnippets = generatePhaserSnippets(normalized.nodes)
  const output: MapperOutput = {
    input: {
      width: normalized.width,
      height: normalized.height,
      title: typeof parsed.title === 'string' ? parsed.title : 'Untitled Stitch Screen',
    },
    layout: normalized.nodes,
    diagnostics: {
      overlaps,
      fitWarnings,
    },
    phaserSnippets,
  }

  if (args.jsonOutPath) {
    await ensureDirForFile(args.jsonOutPath)
    await writeFile(args.jsonOutPath, `${JSON.stringify(output, null, 2)}\n`, 'utf8')
  } else {
    console.info(JSON.stringify(output, null, 2))
  }

  if (args.phaserOutPath) {
    await ensureDirForFile(args.phaserOutPath)
    const contents = [
      '// Generated by stitch-phaser-mapper',
      '// Review and adapt before use in production scenes.',
      '',
      ...phaserSnippets,
      '',
    ].join('\n')
    await writeFile(args.phaserOutPath, contents, 'utf8')
  }

  console.info(
    `stitch-phaser-mapper: nodes=${normalized.nodes.length} overlaps=${overlaps.length} fitWarnings=${fitWarnings.length}`,
  )
}

void run()
